### ISSUE TITLE
Hardware triggering and multi camera

### ISSUE THREAD

**Issue by abrosua** [klecknerlab/simple_pyspin#2]
Hi, first of all, thanks for making this interface that really simplifies the usage of PySpin. I'm trying to use PySpin for multiple camera setup (only 2 in my case for a stereoscopic project) and utilize Hardware triggering to sync both cameras while controlling the FPS using the hardware signal also. Have you tried the triggering feature using this? Or maybe what should/could be modified or added to the current code?

Best regards

**Comment by klecknerlab** [comment]
Thanks, glad someone else is using it!  
To answer your question: I have not triggered two cameras, but I *have* triggered one, with no issues.  I don't think you should have any difficulty getting this to work: any and all settings which are exposed by the API should be accessible.  I have not experimented with using two cameras at once, but I think it should work -- if not let me know.
